### ISSUE TITLE
Is this gem still currently supported and working on the latest version of rails as of 7/9/15?

### ISSUE THREAD

**Issue by EliteViper777** [mixonic/ranked-model#101]

**Comment by radixhound** [comment]
I'm using it in a Rails 5 project. 12/7/16. Works for me.

**Comment by bxt** [comment]
It seems to me that the owner of this repo @mixonic got into JavaScript and Ember.js development and is no longer really maintaining this?

**Comment by mixonic** [comment]
@bxt I'm still around.

> Is this gem still currently supported?

As with most OSS, "support" is a vague status. Do I still have access to the repo? Yes. Have changes landed to master in the last year? Yes. Do I have any active projects myself using this library? No. Are there open PRs that are behind on review? Probably.

Is that enough for your needs? Only you know.

> Is this gem still working on the latest version of rails?

I have no idea. You can find a very detailed list of what library versions are supported [in the travis.yml file](https://github.com/mixonic/ranked-model/blob/master/.travis.yml).

I'm happy to help anyone who uses this library in a real app and would like to step up as a maintainer. You can find my email pretty readily :-D
