### ISSUE TITLE
multi position column

### ISSUE THREAD

**Issue by mm580486** [mixonic/ranked-model#114]
hi guys :)
how to use multi position column with ranked-model ?

for sample :
class Duck < ActiveRecord::Base

  include RankedModel

  ranks :row_order,  
    :column => :column1    

  ranks :row_order,  
    :column => :column2    

  ranks :row_order,  
    :column => :column3

end

**Comment by brendon** [comment]
You need to use a different name for each of your ranks. Have a look here: https://github.com/mixonic/ranked-model#complex-use
