### ISSUE TITLE
ranked model in rails 5

### ISSUE THREAD

**Issue by dickson95** [mixonic/ranked-model#115]
I have an application in Rails 5, everything works fine until it passes to the controller, which assigns numbers negative, without order of view. I have reviewed many times my code but can not find the problem. Gem Can be incompatible with the version of Rails?

In my coffeescript have this, work fine, has reviewed:

 $(document).on "turbolinks:load", ->

```
$ ->
```

  if $('.sortable').length > 0

```
table_width = $('.sortable').width()
cells = $('.table').find('tr')[0].cells.length
desired_width = table_width / cells + 'px'
$('.table td').css('width', desired_width)

$('.sortable').sortable(
  axis: 'y'
  items: '.item'
  cursor: 'move'

  sort: (e, ui) ->
    ui.item.addClass('active-item-shadow')
  stop: (e, ui) ->
    ui.item.removeClass('active-item-shadow')
    # highlight the row on drop to indicate an update
    ui.item.children('td').effect('highlight', {}, 1000)
  update: (e, ui) ->
    item_id = ui.item.data('item-id')
    position = ui.item.index() # this will not work with paginated items, as the index is zero on every page
    console.log position
    $.ajax(
      type: 'POST'
      url: '/colors/update_secuencia'
      dataType: 'json'
      data: { color: {color_id: item_id, secuencia_position: position } }
    )
)
```

return

I leave my code of the controller, where I try to multiply by 1 to move the number to a positive

```
   @color = Color.find(color_params[:color_id])    
   @color.secuencia_position = color_params[:color_position].to_i * (-1)
   @color.save 
   head :no_content  
```

I don't have more configuration in the controller

I have used this tutorial, [http://benw.me/posts/sortable-bootstrap-tables/](url)
Any idea or suggestion?

**Comment by egoens** [comment]
I'd be interested to know if this gem is compatible with Rails 5 too. Any luck finding a solution @dickson95?

**Comment by dickson95** [comment]
No, I could not make this to work.

**Comment by egoens** [comment]
Thanks for letting me know @dickson95. I appreciate it.

**Comment by dickson95** [comment]
You're welcome @egoens. Sorry for long time to answer

**Comment by darrenterhune** [comment]
We have `ranked-model` working with rails 5, nothing special.

**Comment by brendon** [comment]
Hi all, could you please check the latest version of the gem to see if the problem still exists?

**Comment by brendon** [comment]
Closing this for now.
