### ISSUE TITLE
Cannot use :order as column name

### ISSUE THREAD

**Issue by joshlarsen** [mixonic/ranked-model#131]
Perhaps this is more of an FAQ item than a bug, but I'll raise the issue in case anyone wants to comment. If you use `order` as the column name, and `rearrange_ranks` is called, a `PG::SyntaxError` gets thrown as the column name isn't escaped.

##### development.log
```bash
PG::SyntaxError - ERROR:  syntax error at or near "order"
LINE 1: UPDATE "sections" SET order = order + 1 WHERE "sections"."id...
```

##### models/section.rb
```ruby
class Section < ApplicationRecord
  include RankedModel
  ranks :order, with_same: :course_id
  belongs_to :course
end
```

Changing the column name to something other than `order` resolves the issue.

**Comment by brendon** [comment]
@joshlarsen, can you try with `master` as I think we might have just fixed this. If not, let me know.

**Comment by joshlarsen** [comment]
@brendon Yes, that does fix it. Thanks.

**Comment by brendon** [comment]
Excellent :D
