### ISSUE TITLE
Release a new gem

### ISSUE THREAD

**Issue by brendon** [mixonic/ranked-model#134]
Hi @mixonic, I think we should release a new gem with these fixes. Would you be able to give me access to do this? My rubygems email is brendon@spike.net.nz

Also your release procedure would be appreciated :)

**Comment by mixonic** [comment]
@brendon done!

Regarding release procedure I don't believe there is anything special.

* Run the tests on `master`
* Follow https://semver.org/ to choose a version name
* Manually edit `ranked-model.gemspec` with the new version
* `gem build ranked-model.gemspec`
* Presuming success...
* `git commit -am"Bump vX.X.X"` with only the version bump
* `gem push ranked-model-X.X.X.gem`
* `git tag vX.X.X`
* `git push --tags`

**Comment by brendon** [comment]
Thanks Matthew, I've done a release for 0.4.2 (since it's just a bug fix
release) :)

Cheers,

Brendon Muir
