### ISSUE TITLE
 NoMethodError:  undefined method `>' for nil:NilClass

### ISSUE THREAD

**Issue by chrisgeek** [mixonic/ranked-model#135]
Rails 5.1.2
Ruby 2.5
Rspec 3.8
I get this error when trying to create a resource using factorybot's create method,
`create(:assessment, user: admin, assigned_user: behavioral_specialist)`,here is the full error log
```1) Assessment Order returns assessment in desc order
     Failure/Error: @assessment = create(:assessment, user: admin, assigned_user: behavioral_specialist)
     
     NoMethodError:
       undefined method `>' for nil:NilClass
     # ./spec/models/assessment_spec.rb:42:in `block (3 levels) in <main>'
     # ./spec/spec_helper.rb:39:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:38:in `block (2 levels) in <top (required)>'

```

**Comment by geoffharcourt** [comment]
Sorry, I was reporting the issue in #133, which isn't the same thing.

**Comment by chrisgeek** [comment]
@brendon when i comment out RankedModel `include RankedMode` and `ranks :id` from my model.rb class,the test works fine,so my question is,why is RankedModel causing such an error?

**Comment by brendon** [comment]
Sorry @chrisgeek, I didn't realise two different people had posted in this issue already :D I'm totally open to the idea that it's `ranked-model` causing the problem but we need more information really. Post your spec code and your model also.

**Comment by chrisgeek** [comment]
```class Assessment < ApplicationRecord
  include RankedModel
  ranks :id

  belongs_to :user
  belongs_to :assigned_user, class_name: "User"
  has_many :items
  validates :title, presence: true
  validates :assigned_user, presence: true
end
```
my model

**Comment by chrisgeek** [comment]
```  let(:admin) { User.new(email: 'rockcoolsaint@example.com', password: 'password', password_confirmation: 'password', role: :admin) }
  let(:behavioral_specialist) { User.new(email: 'bs@example.com', password: 'password', password_confirmation: 'password', role: :behavioral_specialist) }

  describe 'Order' do

    it 'returns assessment in desc order' do

      @assessment = create(:assessment, user: admin, assigned_user: behavioral_specialist)
      @assessments = Assessment.rank(:id).where(assigned_user_id: behavioral_specialist.id).first
      expect(@assessment).to eq(@assessments)

    end
  end
```
snippet from spec file

**Comment by brendon** [comment]
My first suspicion would be around you using the `id` as your position column. You should use something else unless you have a good reason. The `id` column is used by Rails and I doubt the two would place nice together. Give that a go and see how you get on. You could call the column `row_order` or anything else really.

**Comment by brendon** [comment]
In your model you'll need:

`
include RankedModel
ranks :row_order
`

Then on your table you'll need a `:row_order` column.

**Comment by chrisgeek** [comment]
Yea,you are right,it works fine with `row_order` or any other name except `id`,i will have to close this issue then.

**Comment by brendon** [comment]
Glad you figured it out :)
