### ISSUE TITLE
NoMethodError undefined method `<' for nil:NilClass after 0.4.2 upgarde

### ISSUE THREAD

**Issue by rchrand** [mixonic/ranked-model#136]
I'm getting this error after upgrading from `0.4.1 -> 0.4.2`. Downgrading makes it work again.

Our code:
```ruby
class Tagging < ApplicationRecord
  include RankedModel

  belongs_to :tag
  belongs_to :taggable, polymorphic: true

  ranks :position, with_same: %i[taggable_id taggable_type]
end
```

It occurs when trying to add multiple tags in a single action, but adding them individually seems to work.

Stacktrace from Sentry:
![image](https://user-images.githubusercontent.com/2136481/50006648-b7edaf80-ffae-11e8-8c46-b839e6740381.png)

**Comment by brendon** [comment]
Hi @rchrand, sorry to hear you're having trouble. Would you be able to do up a PR with a failing test so we can isolate what's happening?

**Comment by jerhinesmith** [comment]
I'm running into the same issue after updating. I'm trying to get some more info - will post more if I can.

**Comment by jerhinesmith** [comment]
I tried to repro this morning by following the steps in `Contributing` but got into a mess with mysql not being installed locally. I'll try again tonight if I get some time. 🙁

**Comment by brendon** [comment]
That's weird. The tests don't run without appraisal (I haven't set up defaults) try `bundle exec appraisal install` after `bundle`. Also check out `database.yml` to make sure the settings there are correct for your environment. I typically have to change the Postgres user.

**Comment by brendon** [comment]
You will also need to create the appropriate database on the database server too I think.

**Comment by jerhinesmith** [comment]
It threw an exception trying to install the MySQL gem while running appraisal install  - I think because I don’t have MySQL installed on my Mac (it was a compile error, if I remember correctly).

**Comment by brendon** [comment]
Oh ok, yea that's weird. I have MySQL here so I guess you'll need to try installing it if that's ok? :)

**Comment by frostblooded** [comment]
I am having the same issue, but am not using the gem directly. Updating all of my gems results in [this](https://pastebin.com/7qVSkdrw) spec (and many others) failing.

**Comment by brendon** [comment]
I think this might be to do with a rebalancing running when we attempt to add a new record to the list. When I get time, I'll investigate that. In the meantime, if someone can come up with a test case that'd be super helpful :D

**Comment by thatdom** [comment]
same issue for us

**Comment by brendon** [comment]
Thanks @thatdom, if you could dig a bit deeper into why this happening for you that'd be helpful. Right now we don't really have a cause identified but I have a hunch:

Inserting into a full list:
```
      def rank_at_average(min, max)
        if (max - min).between?(-1, 1) # No room at the inn...
          rebalance_ranks
          position_at position
        else
          rank_at( ( ( max - min ).to_f / 2 ).ceil + min )
        end
      end
```
triggers `rebalance_ranks`:
```
def rebalance_ranks
        if rank
          origin = current_order.index { |item| item.instance.id == instance.id }
          destination = current_order.index { |item| rank <= item.rank }
          destination -= 1 if origin < destination

          current_order.insert destination, current_order.delete_at(origin)
        end

        gaps = current_order.size + 1
        range = (RankedModel::MAX_RANK_VALUE - RankedModel::MIN_RANK_VALUE).to_f
        gap_size = (range / gaps).ceil

        current_order.each.with_index(1) do |item, position|
          new_rank = (gap_size * position) + RankedModel::MIN_RANK_VALUE

          if item.instance.id == instance.id
            rank_at new_rank
          else
            item.update_rank! new_rank
          end
        end

        reset_cache
      end
```

Now before we rebalance, we reshuffle the `current_order` which is the list of records from the database (memoized) to reflect our desired new rank. We only do this if the ranking column isn't nil.

My suspicious is that you're all setting the rank column directly for a new record that doesn't exist in the database yet. And the code is assuming that if the rank column is set, then the record is persisted and exists in `current_order`.

Generally, setting the ranking column isn't encouraged. You're better to position relative to the position of another existing element in the list (get this by querying the element) using the pseudo-column, or use one of the other symbol helpers (`:first`, `:last` etc...)

We make these methods for you:

```
    attr_reader "#{ranker.name}_position"
      define_method "#{ranker.name}_position=" do |position|
        if position.present?
          send "#{ranker.column}_will_change!"
          instance_variable_set "@#{ranker.name}_position", position
        end
      end
```

So for example (@rchrand): `tagging.position_position = 3` will set the position so that this `tagging` is the 4th in the list (0 based index).

I hope that helps everyone. If you still have an issue with how this works, please do put in a test case that highlights the problem and we can look at fixing it. I think in the future I might make if more difficult to set the raw rank column directly.

**Comment by tylerjolmstead** [comment]
We are also encountering this issue, here's our setup:

```ruby
class CannedJobInventory < ApplicationRecord
  include RankedModel

  belongs_to :canned_job, inverse_of: :parts
  ranks :row_order, with_same: :canned_job_id
end

class CannedJob < ApplicationRecord
  has_many :labors, class_name: CannedJobLabor.name, dependent: :destroy
end
```

What appears to be happening in our case (abbreviated):
```ruby
CannedJob.new(cj_attributes).tap do |canned_job|
   ...
  past_service.parts.rank(:row_order).each do |part|
    canned_job.parts.build(part.attributes_to_copy)
  end
  ...
  canned_job.save! # exception thrown
end
```

Note that in this case `past_service` is an `ActiveRecord` model that we are copying data from; I think the details are not relevant. Without understanding the implementation of this gem, I am guessing that the exception is triggered because we are adding several ranked `CannedJobInventory` to the `CannedJob` before it has an ID, then saving. Please let me know if this is helpful, or if there's something else we should be doing.

**Comment by richardonrails** [comment]
I also got this error after the 0.4.2 upgrade.

Here's a snippet of our models:

```rb
class Category < ActiveRecord::Base
  belongs_to :site
  has_many :articles, dependent: :nullify
  include RankedModel
  ranks :row_order, with_same: :site_id
  # ...
end

class Article < ActiveRecord::Base
  belongs_to :site
  belongs_to :category, counter_cache: true
  include RankedModel
  ranks :row_order, with_same: [:site_id, :category_id]
  # ...
end
```

**Comment by brendon** [comment]
Hi everyone. I've been on holiday, so I'll reply to you all below:

@m0n9oose, Are you able to check if the error still occurs when you remove the default column value? Off the top of my head, we check for rank to confirm if the current record already has an assigned rank. We assume from this that the record is persisted. Perhaps the check should instead be for `persisted?` or both `rank && persisted?`.

In your case, looking at the rebalancing code, having a default value for rank would make the rebalanced assume that it had already assigned a rank in the past, and that the rank was successfully saved.

@tylerjolmstead and @richardonrails, thank you both for your examples. @tylerjolmstead, your examples shows that you're probably inadvertently assigning `rank` when you copy the attributes (thus triggering the bug). @richardonrails, I can't see from what you've provided how you'd triggering it, but it's probably something similar. What I'll do is create a branch where we check for `persisted?` and `rank`. Can you try this branch out and let me know how you get on?

**Comment by brendon** [comment]
Everyone, please try https://github.com/mixonic/ranked-model/tree/fix-nil and report back.

**Comment by dlandau** [comment]
I just encountered this issue and removing the default value (of 0) on my row_order column appears to have resolved it.

**Comment by brendon** [comment]
Yes, I suspected it would. I don't think there's a need to set a default value for this column as it's internally managed. You could set a not-null constraint though and that should be enough.

**Comment by richardonrails** [comment]
>  @richardonrails, I can't see from what you've provided how you'd triggering it, but it's probably something similar.

The error was triggering me from `@article.save` in the following snippet, from a pretty standard controller / form combination.

```
class ArticlesController < ApplicationController
  def new
    @article = Article.new(site: @site)
  end

  def create
    @article = Article.new(article_params)
    @article.site = @site
    saved = @article.save   ######## <=== error here
    # ...

  private
    # ...
    def article_params
      permitted_params = [:title, :category_id, :row_order_position]
      params.require(:article).permit(permitted_params)
    end
end
```

**Comment by brendon** [comment]
@richardonrails, that looks standard to me. Can you check you don't have a default value on the `row_order` column? Also, just try the branch above to see if that fixes it for you anyway.

**Comment by richardonrails** [comment]
Indeed it looks like one (`Article`) of my `row_order` columns has `default: 0, null: false` whereas the other (`Category`) doesn't have either.

Do I need to run a migration to drop the default value? And also one to make it null: true? Or does this not matter in the updated version? (I won't have a chance to play with it for a while)

**Comment by brendon** [comment]
You can have a null constraint on there if you like. Something went wrong if ranked-model didn't set a rank. You can remove the default with something like this in your migration:

```
change_column_default :articles, :row_order, nil
```

https://stackoverflow.com/questions/25357171/removing-default-value-from-rails-migration

**Comment by AJMiller** [comment]
@brendon we have had the exact same problem. The same line 211 blows up in `rebalance_ranks`. Switching to `fix-nil` did not solve it.

**Comment by AJMiller** [comment]
@brendon it looks like our schema file has a default value assigned and, fwiw, the default value in our system is set to max int:

```
t.integer "row_order", default: 2147483647, null: false
```

The weird part is everything is fine on 0.4.1. It only breaks on 0.4.2?

**Comment by brendon** [comment]
Hi @AJMiller, thanks for the update. It's not necessary to set a default value, you can just let the gem do that. It breaks due to our assumption that new records won't have a rank set until they're persisted.

**Comment by AJMiller** [comment]
dropping the default value worked for us as well. Thank you @brendon! For those on rails 5.x+ you can create a reversible migration this way:

```ruby
class RemoveDefaultForRowOrder < ActiveRecord::Migration[5.2]
  def change
    change_column_default(:my_table_name, :row_order, from: 0, to: nil)
  end
end
```

**Comment by brendon** [comment]
You might be right there :) Either that or we can alert people when they try to set this column outside of ranked-model. What do you think?

**Comment by brendon** [comment]
I'm thinking of a README message for now. The test suite makes use of explicitly setting the column value so there's some complication there around adding a warning. For now I'll also not merge the `fix-nil` branch since the better way to sort this is to remove the default value for this column.

I'll investigate adding an error on app boot if we detect a default value for the column.

**Comment by brendon** [comment]
Lol, so I've gone the other direction. I did merge the check for `persisted?` as that makes sense. I've also added raising an error if a ranked model column has a default value on app boot. I've not bothered with the README message as the error raised will catch all instances of this issue and it gives the solution.

@tylerjolmstead, your case is a bit more unique. Can you test that your case is solved with the check for `persisted?` in the latest version?

**Comment by brendon** [comment]
Released as 0.4.3

**Comment by richardonrails** [comment]
I'll try to post more details about it later, but just FYI when upgrading to 0.4.3 or 0.4.4 some of the ordering on my site stops working properly.

**Comment by brendon** [comment]
Hi @richardonrails, thanks for the heads up. Be sure to post that as a new issue to help keep things organised :)
