### ISSUE TITLE
#{column_name}_rank is undefined

### ISSUE THREAD

**Issue by rmammina** [mixonic/ranked-model#138]
I tried using the newly release feature of getting  relative rank, but am getting an undefined method error.

**Comment by brendon** [comment]
Hi @rmammina, can you provide some more information? Perhaps a stack trace?

**Comment by dhnaranjo** [comment]
I encountered the same issue but discovered it wasn't actually an issue. The PR rmammina is referring to, https://github.com/mixonic/ranked-model/pull/137, isn't in a released version yet.

**Comment by brendon** [comment]
Lol, yes that'd be it :) We do plan to do a release but there is more to come on this feature so we're waiting on that to be settled first :)
