### ISSUE TITLE
Any db calls within a spec hang

### ISSUE THREAD

**Issue by dudo** [mixonic/ranked-model#142]
Hello! So my specs started hanging once including this gem. I dug around quite a bit, and 0.4.2 seems to work fine. The db checks you put into place seem to be hanging. I ran the gem locally with a binding.pry, and any calls to the db just hangs. 

https://github.com/puma/puma/commit/b94c3e34faff024a5b1930af36e4d64bd6dde57f#diff-c2ca2259d38a531715284b3ec3f4b698

Seems as though it might be related to this?

Setup is as follows:
- ruby 2.6.2p47
- Rails 5.2.3
- psql (11.1, server 10.6 (Debian 10.6-1.pgdg90+1))

Any idea what might be happening? or any more info I can give to help understand what's happening? In the meantime, I'm locked to 0.4.2, so I'm not blocked.

**Comment by brendon** [comment]
Hi Brett, thanks for this. It's a strange one. Can you try bundling each commit on master in succession to see if we can isolate the exact commit that broke this? We're not doing too much magical other than checking first `ActiveRecord::Base.connected?` and then if that is true we check the default value for the rank column in the database. This happens at app boot.

Keep me posted on your investigations :)

**Comment by dudo** [comment]
To add a tiny bit of flavor, it only hangs during system tests, being driven by selenium (capybara), and it only seems to happen within your gem with 0.4.3 and higher. I have 0.4.2 installed, like I said, and I can't reproduce it. Super weird.

**Comment by brendon** [comment]
Thanks @dudo. I think it'll definitely be related to the initial database check. The easiest way to check is to clone the repo locally and bundle it in as a local dependency in your `Gemfile`, then try commenting out the database check for a default value. Perhaps this all malfunctions with database connection sharing (as is done to ensure the capybara thread shares the same database connection as the main thread? I'm not sure if you're doing this hack or not?

**Comment by brendon** [comment]
We could look at something like this instead of checking if the database is connected? https://github.com/rails/rails/pull/31681#issuecomment-357113030

**Comment by dudo** [comment]
@brendon I fixed this by adding this to my system tests...

```Capybara.server = :puma, { Silent: true, Threads: '1:1' }```

**Comment by brendon** [comment]
Interesting. Sounds like a database deadlocking issue?
