### ISSUE TITLE
Ranks next to each other

### ISSUE THREAD

**Issue by trickkiste** [mixonic/ranked-model#63]
After 22 items in my ranked-model, the ranks already are exactly next to each other! 

Why is this? 
Am I doing something wrong? 
Or is this thing not build for lists larger than 20 items?

My initial list is created in order. 
I basically append new items to the bottom. 
No reordering until I have enough clips in my list.

Can I make ranked-model re-rank all my items in the list?

Here is my model:

```
class ScheduledClip < ActiveRecord::Base
  include RankedModel

  belongs_to :video
  belongs_to :scheduled_block
  attr_accessible :duration, :position, :uuid, :is_ad, :is_filler, :xml, :video_id, :scheduled_block_id, :nb_frames, :frame_rate

  ranks :block_order, :column => :position, :with_same => :scheduled_block_id
end
```

This is the result of ScheduledBlock.find(30).scheduled_clips.rank(:block_order)

position: 0, video_id: 8811, block_order: -73
position: 1, video_id: 8802, block_order: 4194231
position: 2, video_id: 8988, block_order: 6291383
position: 3, video_id: 7830, block_order: 7339959
position: 4, video_id: 8094, block_order: 7864247
position: 5, video_id: 8040, block_order: 8126391
position: 6, video_id: 8196, block_order: 8257463
position: 7, video_id: 11888, block_order: 8322999
position: 8, video_id: 9031, block_order: 8355767
position: 9, video_id: 8815, block_order: 8372151
position: 10, video_id: 9084, block_order: 8380343
position: 11, video_id: 7822, block_order: 8384439
position: 12, video_id: 8977, block_order: 8386487
position: 13, video_id: 8914, block_order: 8387511
position: 14, video_id: 9109, block_order: 8388023
position: 15, video_id: 7828, block_order: 8388279
position: 16, video_id: 8233, block_order: 8388407
position: 17, video_id: 8106, block_order: 8388471
position: 18, video_id: 8216, block_order: 8388503
position: 19, video_id: 7836, block_order: 8388519
position: 20, video_id: 8877, block_order: 8388527
position: 21, video_id: 8953, block_order: 8388531
position: 22, video_id: 8795, block_order: 8388533
position: 23, video_id: 11886, block_order: 8388534
position: 24, video_id: 8108, block_order: 8388535
position: 25, video_id: 8222, block_order: 8388536
position: 26, video_id: 8162, block_order: 8388537
position: 27, video_id: 11821, block_order: 8388538
position: 28, video_id: 9081, block_order: 8388539
position: 29, video_id: 9124, block_order: 8388540
position: 30, video_id: 8985, block_order: 8388541
position: 31, video_id: 12805, block_order: 8388542
position: 32, video_id: 8805, block_order: 8388543
position: 33, video_id: 8782, block_order: 8388544
position: 34, video_id: 8916, block_order: 8388545
position: 35, video_id: 11821, block_order: 8388546
position: 36, video_id: 9131, block_order: 8388547
position: 37, video_id: 11317, block_order: 8388548
position: 38, video_id: 9013, block_order: 8388549
position: 39, video_id: 12094, block_order: 8388550
position: 40, video_id: 8111, block_order: 8388551
position: 41, video_id: 8082, block_order: 8388552
position: 42, video_id: 8070, block_order: 8388553
position: 43, video_id: 7830, block_order: 8388554
position: 44, video_id: 8843, block_order: 8388555
position: 45, video_id: 8958, block_order: 8388556
position: 46, video_id: 9004, block_order: 8388557
position: 47, video_id: 11821, block_order: 8388558
position: 48, video_id: 9085, block_order: 8388559
position: 49, video_id: 8806, block_order: 8388560
position: 50, video_id: 8986, block_order: 8388561
position: 51, video_id: 7824, block_order: 8388562
position: 52, video_id: 8200, block_order: 8388563
position: 53, video_id: 8163, block_order: 8388564
position: 54, video_id: 7983, block_order: 8388565
position: 55, video_id: 11821, block_order: 8388566
position: 56, video_id: 8092, block_order: 8388567
position: 57, video_id: 8004, block_order: 8388568
position: 58, video_id: 8144, block_order: 8388569
position: 59, video_id: 7826, block_order: 8388570
position: 60, video_id: 9020, block_order: 8388571
position: 61, video_id: 8817, block_order: 8388572
position: 62, video_id: 8839, block_order: 8388573
position: 63, video_id: 7831, block_order: 8388574
position: 64, video_id: 8999, block_order: 8388575
position: 65, video_id: 8834, block_order: 8388576
position: 66, video_id: 9019, block_order: 8388577
position: 67, video_id: 7826, block_order: 8388578
position: 68, video_id: 8868, block_order: 8388579
position: 69, video_id: 8909, block_order: 8388580
position: 70, video_id: 9003, block_order: 8388581
position: 71, video_id: 11820, block_order: 8388582
position: 72, video_id: 12332, block_order: 8388583
position: 73, video_id: 12324, block_order: 8388584
position: 74, video_id: 12320, block_order: 8388585
position: 75, video_id: 7826, block_order: 8388586
position: 76, video_id: 8121, block_order: 8388587
position: 77, video_id: 8218, block_order: 8388588
position: 78, video_id: 8109, block_order: 8388589
position: 79, video_id: 11820, block_order: 8388590
position: 80, video_id: 8788, block_order: 8388591
position: 81, video_id: 9087, block_order: 8388592
position: 82, video_id: 8785, block_order: 8388593
position: 83, video_id: 11784, block_order: 8388594
position: 84, video_id: 8076, block_order: 8388595
position: 85, video_id: 8132, block_order: 8388596
position: 86, video_id: 8160, block_order: 8388597
position: 87, video_id: 7828, block_order: 8388598
position: 88, video_id: 8945, block_order: 8388599
position: 89, video_id: 9050, block_order: 8388600
position: 90, video_id: 8871, block_order: 8388601
position: 91, video_id: 11886, block_order: 8388602
position: 92, video_id: 11741, block_order: 8388603
position: 93, video_id: 11740, block_order: 8388604
position: 94, video_id: 11742, block_order: 8388605
position: 95, video_id: 11820, block_order: 8388606
position: 96, video_id: 11754, block_order: 8388607

**Comment by brendon** [comment]
This is fixed in master and hopefully in a new gem release soon. When the last gap is taken, the next attempt to insert at the end of the list will result in the list being rebalanced.
