### ISSUE TITLE
Not working for the existing data

### ISSUE THREAD

**Issue by stgeneral** [mixonic/ranked-model#75]
I've added a ranked_model to the existing data and filled in row_order with 0 as a default value (remember that we can't have null values #73).

``` ruby
# initial state:
Duck.count # 4
Duck.update_all('row_order = 0')

# test cases (revert to initial stage before each):
@duck.update_attribute :row_order_position, 0 # works fine
@duck.update_attribute :row_order_position, 1 # does nothing
@duck.update_attribute :row_order_position, 2 # does nothing
@duck.update_attribute :row_order_position, 3 # works fine
```

I've solved this issue by updating row_order for existing data with an id value.
This case should be handled or at least documentation updated. 

This issue probably describes the same problem noted in #67.

**Comment by fwolfst** [comment]
If that is still an issue, adding an examplary migration to the README that sets the row_order equal to to id of each record would be nice for fellow users.

**Comment by brendon** [comment]
Looks good to me. I'll merge that migration documentation. For @elfassy, I wasn't working on this project then, but I'd suspect that he wasn't ordering the table on `:row_order` before calling `.first` or `.last`.
