### ISSUE TITLE
Ranking with_same through association

### ISSUE THREAD

**Issue by willcosgrove** [mixonic/ranked-model#89]
Here's my setup

``` ruby
# area.rb
class Area < ActiveRecord::Base
  has_many :tasks
end

# task.rb
class Task < ActiveRecord::Base
  belongs_to :area
  has_many :project_tasks
end

# project_task.rb
class ProjectTask < ActiveRecord::Base
  belongs_to :task
  belongs_to :project # not relevant for this example, for for completeness sake
  has_one :area, through: :task

  ranks :area_order, with_same: :area_id # Doesn't work because there's not an area_id column on project_tasks
end
```

I'm not sure how to solve this.  I could cache `area_id` on the `project_task`, but that seems messy, and I'd then have to deal with making sure that always stays in sync.  Is there anyway to use RankedModel's `with_same` feature with a joined attribute?

Also, thanks for making this awesome gem!  It's saved me tons of time.

**Comment by brendon** [comment]
Closing this for now. Perhaps there would be a way if the default scope included a join? You've probably moved on after 10 years :D

**Comment by yannickgloster** [comment]
This is something I'm looking to figure out as well, it doesn't look like adding a default scope with the join affects the query that is being produced.

**Comment by brendon** [comment]
True, as I think we unscope on purpose to keep our queries clean. I could imagine opening things up to scope could get out of hand pretty quickly. Still, would be an interesting exercise. Perhaps it'd be simpler to try it out on my other gem that has a much more straightforward codebase: https://github.com/brendon/positioning?

**Comment by brendon** [comment]
Perhaps a virtual column could work?

**Comment by yannickgloster** [comment]
I'll take a look at the other gem. I think realistically for this, I'll end up copying the ID on the parent to the child and keeping them in sync with callbacks.
