### ISSUE TITLE
Ranker#rearrange_ranks produces invalid SQL when column is named 'order'

### ISSUE THREAD

**Issue by janfoeh** [mixonic/ranked-model#90]
When using an order column named 'order':

```
class PlaylistPosition < ActiveRecord::Base
  include RankedModel

  ranks :order, with_same: :playlist_id

  belongs_to :playlist
  belongs_to :story
end
```

ranked-model produces this query

```
UPDATE "playlist_positions" SET order = order - 1 WHERE "playlist_positions"."id" IN (SELECT "playlist_positions"."id" FROM "playlist_positions" WHERE "playlist_positions"."playlist_id" = 7 AND ("playlist_positions"."order" <= 8388607)  ORDER BY "playlist_positions"."order" ASC);
ERROR:  syntax error at or near "order"
LINE 1: UPDATE "playlist_positions" SET order = order - 1 WHERE "pla...
```

in [Ranker#rearrange_ranks](https://github.com/mixonic/ranked-model/blob/master/lib/ranked-model/ranker.rb#L180) with Postgres 9.4.0 / Rails 4.2.0.

I've fixed it by simply renaming the column, but I wanted to report it anyway. SQL syntax is not my strongest suit, but could the fix be to simply quote the column name?

**Comment by mkalygin** [comment]
@janfoeh have you found a solution to this?

I experience the same issue. And for the most part it happens randomly in my rspec tests. Can anybody explain why does it happen?

My ranked column name is `order`. PostgreSQL 10.1, Rails 5.1.4.

Backtrace:
```
# .../ranked-model-0.4.0/lib/ranked-model/ranker.rb:184:in `rearrange_ranks'
# .../ranked-model-0.4.0/lib/ranked-model/ranker.rb:166:in `assure_unique_position'
# .../ranked-model-0.4.0/lib/ranked-model/ranker.rb:61:in `handle_ranking'
# .../ranked-model-0.4.0/lib/ranked-model.rb:31:in `block in handle_ranking'
# .../ranked-model-0.4.0/lib/ranked-model.rb:30:in `each'
# .../ranked-model-0.4.0/lib/ranked-model.rb:30:in `handle_ranking'
```

**Comment by janfoeh** [comment]
@mkalygin sorry, but it's been quite a while. From a quick look I'd say my guess back then still looks pretty good — if you cannot rename the column, try quoting the column name in all `update_all` calls in `ranker.rb`.

If that gives you a syntax error, I would try adressing the column explicitely through the `tablename.column_name` syntax. ie. something like 

```ruby
update_all( %Q("#{instance.class.name.tableize}"."#{ranker.column}" = #{instance.class.name.tableize}"."#{ranker.column}" - 1) )
```

**Comment by mkalygin** [comment]
@janfoeh yeah, I've submitted PR with this fix. Let's see if this correct or not. 😄

**Comment by balen** [comment]
Any idea when there will be a version release for this? Thanks.

**Comment by brendon** [comment]
I'm not sure. @mixonic, would you be able to give me gem release rights? And also the steps you use to release a gem?
