### ISSUE TITLE
Ordering from last up one, moves it to second

### ISSUE THREAD

**Issue by dsandstrom** [mixonic/ranked-model#92]
Rails 4.2, Ruby 2.2, ranked-model 0.4

I'm using ranked-model on several tables and have noticed a weird behavior.  When I have at least 4 items and try to reorder the last item up one position, it gets bumped up to second place.

I was able to reproduce in a controller test, so I think it is a bug.  I can make an example app this weekend if need be.

Here is one model:

``` ruby
class Tag < ActiveRecord::Base
  include RankedModel
  ...
  ranks :row_order
  default_scope { order(:row_order) }
 ...
end
```

This test doesn't pass, it results in [first, fourth, second, third].  I expect [first, second, fourth, third]

``` ruby
it "orders the tags" do
  first = create(:tag)
  second = create(:tag)
  third = create(:tag)
  fourth = create(:tag)

  put :update, { id: fourth.to_param, tag: { row_order_position: 'up' } }
  expect(Tag.all).to eq [first, second, fourth, third]
end
```

Ordering down works as expected.

**Comment by dsandstrom** [comment]
After further testing, it's not a problem when just ordering the last element.  Anything lower than the second position, gets bumped to second.

**Comment by dsandstrom** [comment]
A workaround is use `each_with_index` then use `@duck.update_attribute :row_order_position, index - 1` instead of `:up`.

**Comment by brendon** [comment]
@dsandstrom, can you check if this problem still exists? I think we solved it with a patch in the latest version of the gem.

**Comment by brendon** [comment]
Also try `master`

**Comment by joshlarsen** [comment]
FYI, this still happens on `0.4.1` and `0.4.2` and `master` as of Dec. 14, 2018.

**Comment by brendon** [comment]
@joshlarsen, would you be able to create a PR with a failing test? I'm keen to squash these kinds of bugs.

**Comment by joshlarsen** [comment]
@brendon I wasn't able wrap my head around how the tests are currently set up when scoped `with_same:`. However, I did create a little mini app to demonstrate.

> source
[https://github.com/joshlarsen/ranked-model-test](https://github.com/joshlarsen/ranked-model-test)

```ruby
class Stock < ApplicationRecord
  include RankedModel
  ranks :rank, with_same: :portfolio_id
  belongs_to :portfolio
  default_scope { order 'stocks.rank ASC' }
end
```

> app
[https://whispering-beyond-51012.herokuapp.com/](https://whispering-beyond-51012.herokuapp.com/)

Expected behavior:
- sort up moves record up one position
- sort down moves record down one position

Actual behavior:
- sort up moves record into second position
- sort down moves record down one position

The Heroku app is running with `0.4.2`, but it seems to work the same in the current `master` branch as well.

**Comment by brendon** [comment]
Ok, so I had a good play with your app. Firstly I think it's the default scope on the Stock model that is causing the grief. I removed that line and changed the `has_many` to this:

`has_many :stocks, -> { order('stocks.rank ASC') }, dependent: :destroy`

Then in your controller:

```
def index
  @stocks = Portfolio.first.stocks
end
```

Now the ordering methods work well. However, `ranked-model` should be able to cope with a default order so perhaps that needs looking into :)

**Comment by brendon** [comment]
I've made a tweak on master (`reorder` rather than `order`) that should overcome your default scope (so you can try keeping it). I've tested it with your test app and it now works, though I'd advise against using `default_scope` ordering if you can help it.

**Comment by joshlarsen** [comment]
Good point about the default scope. I should have thought to try an alternate to that. I can do without that. Thanks for looking into it.
