### ISSUE TITLE
Error when placing new elements at front of list by default

### ISSUE THREAD

**Issue by andialles** [mixonic/ranked-model#99]
I have a list, where I put new Models in front of the list like so:

``` ruby
class Duck < ActiveRecord::Base
  include RankedModel

  belongs_to :pond
  ranks :swimming_rank, with_same: :pond_id

  def append_to(duck = nil)
    position = duck ? duck.swimming_rank + 1 : :first
    self.update_attribute :swimming_rank_position, position
  end
end
```

By doing this twice I get:

```
1.9.3-p551 :021 > Duck.all.pluck(:swimming_rank)
 => [0, -4194303]
```

When I try to append a Duck to the Duck with rank == 0, the new one gets inserted like that:

```
1.9.3-p551 :021 > Duck.all.pluck(:swimming_rank)
 => [0, -4194303, -2097151]
```

Not at swimming_rank 4194303 as desired.

**Comment by mcfiredrill** [comment]
Having the same issue. Not really sure how the code is supposed to work:

https://github.com/mixonic/ranked-model/blob/master/lib/ranked-model/ranker.rb#L115

**Comment by brendon** [comment]
@andialles, I know it's a long time ago, but I think the code should be:

```
def append_to(duck = nil)
    position = duck ? duck.swimming_rank_position + 1 : :first
    self.update_attribute :swimming_rank_position, position
  end
```

Updating the `:*_position` pseudo-column requires that you set an index value that is `0`-based (not the underlying value in the column stored in the database. `swimming_rank_position` will return the `0`-based index of the duck.

**Comment by andialles** [comment]
Ok. I'm not anymore working for the company I was doing this for. xD. But thanks for the reply.

Am 19. Oktober 2018 06:01:29 MESZ schrieb Brendon Muir <notifications@github.com>:
>@andialles, I know it's a long time ago, but I think the code should
>be:
>
>```
>def append_to(duck = nil)
>    position = duck ? duck.swimming_rank_position + 1 : :first
>    self.update_attribute :swimming_rank_position, position
>  end
>```
>
>Updating the `:*_position` pseudo-column requires that you set an index
>value that is `0`-based (not the underlying value in the column stored
>in the database. `swimming_rank_position` will return the `0`-based
>index of the duck.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mixonic/ranked-model/issues/99#issuecomment-431238013

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by brendon** [comment]
All good :D
